### ISSUE TITLE
Stub Choreo for desired path mirroring

### ISSUE THREAD

**Issue by bryceroethel** [Greater-Rochester-Robotics/GRRBase#23]
By default, ChoreoLib's trajectories maintain a blue alliance field origin and simply flip across the field's width. We always use [WPILib's Field Origin](https://docs.wpilib.org/en/stable/docs/software/advanced-controls/geometry/coordinate-systems.html#field-coordinate-system) to maintain consistency, so ChoreoLib should be stubbed to override their `flip` methods.

**Comment by JackJ09** [comment]
Resolved by #25
