### ISSUE TITLE
Integrate new vision coprocessor + camera

### ISSUE THREAD

**Issue by lydiahays** [Greater-Rochester-Robotics/GRRBase#3]
@BR88C updated our visual library for limelight. Get it running on a limelight, familiarize ourselves with the settings, and verify it has what we need for 2024. This does not need the robot, just the laptop.

**Comment by bryceroethel** [comment]
Current Java API for interacting with the vision pipeline via NT can be found [here](https://github.com/Greater-Rochester-Robotics/GRRBase/blob/main/src/main/java/org/team340/lib/blacklight/Blacklight.java). Needs to be updated to support the new coprocessor-side NT API.

The Java API will likely be pulled out of GRRBase and moved to a separate repository with the pipeline code for easier version management. Investigate utilizing WPILib's [vendordep](https://docs.wpilib.org/en/stable/docs/software/vscode-overview/3rd-party-libraries.html) dependency system for importing the Java API into robot code.

**Comment by bryceroethel** [comment]
Closing as the plan to use the custom vision pipeline has changed.
